### ISSUE TITLE
Create HashMap Library

### ISSUE THREAD

**Issue by bama4** [bama4/simple-http-server#11]
**Description**
This ticket involves implementing a hashmap library. The `hashmap` library should be under the `utils` top level directory.

This `hashmap` library should be linked with all of the other util packages into one library called `libutils.so`

This will be implemented as:
* Open address
* Linear Probing
* A load capacity of 0.75

(See [Open Addressing](https://www.geeksforgeeks.org/hashing-set-3-open-addressing/))

**Goal**
The following functions are created for the hashmap:
- [x] Function for mapping string key to index

Also:
- [x] Write unit tests for the hashmap

**Comment by garfr** [comment]
I think a hashmap is going to be pretty heavily used.  Have you considered writing a generic implementation so we can reuse it?  Like one that takes function pointers to the hashing functions for example.  We could always write a type-safe wrapper over it for a specific use.  Writing a good hashmap is not a trivial task, and if this is a forward-facing web server we ought to put at least a bit of thought into security.

**Comment by garfr** [comment]
I am also not sure if hashmap needs its own directory, as it should fit into a single source and header file.  Building it into its own library and linking against the libutils.so library seems overly complex.

**Comment by bama4** [comment]
> I am also not sure if hashmap needs its own directory, as it should fit into a single source and header file.  Building it into its own library and linking against the libutils.so library seems overly complex.

It was a mistake, as we agreed, all of the utility libraries can be under a single utils directory
