### ISSUE TITLE
Create easy, automated way to run unit tests.

### ISSUE THREAD

**Issue by garfr** [bama4/simple-http-server#5]
# Description
There should be a simple way to run all unit tests in a sub-directory or the entire project.  

The automated test should:
* Allow for the mocking out of external dependencies.
* Allow for the testing of static methods inside a source file.
* Have an option to keep the test executable produced.

This could be achieved with the introduction of a testing framework, but make sure to keep an eye open for uneeded complexity.  We could also hand-roll our own testing framework to exactly suit our needs but this could be a large time sink.

Testing policy specified here: [Simple HTTP Server Testing](https://docs.google.com/document/d/1wsPkHVC7nRPBlAtfjIerxX5wLA5Bi7HlrIm3U5G9k6w/edit#heading=h.qr7giuow7oey)

# Goals

- [x] Decide upon a framework or methodlogy for unit testing
- [x] Integrate it into our workflow with easy to execute scripts.

**Comment by bama4** [comment]
It appears that there is no one way to unit test C code.
My suggestion is to write one test function for every C code function. In terms of mocking, one can write the function declaration in the test file in order to "mock" out the original definition of the dependencies of the function being tested.

Example:

```
//my code.c
int my_func(int var){
   return 3 + var;
}

//test_framework.h
#define SUCCESS 1
#define FAIL 0
#define ASSERT(expr) (expr)? SUCCESS:FAIL

//test_my_code.c
int test_my_func(){
int result = 0;
int neg_var = -4;
//Test negative integer less than -3
result = ASSERT(neg_var < 0);
if(result == FAIL)
   goto leave

//Test positive integer
int pos_var = 4;
result = ASSERT(pos_var > 0);
if(result == FAIL)
   goto leave

leave:
   return result;

}
```

**Comment by garfr** [comment]
We could wrap returning into a macro like
```c
#define ASSERT(expr) if (!(expr)) return FAIL;
```

With that a test could just be:
``` c
int test_my_func() {
    int my_val = 0;
    ASSERT(my_val == 0);

    return SUCCESSS
}
```

I also think that it's worth creating a "unit_test.h" file containing some macros and tools to make the unit testing easier. Things like ASSERT_FALSE, ASSERT_EQ, and ASSERT_STR_EQ seem like no-brainers.  

We could also write a little script that would generate a file of unit test stubs from a source file, even going as far as to have it generate a main function that calls all the unit test functions with logging and stuff.
