### ISSUE TITLE
Create Queue Library

### ISSUE THREAD

**Issue by bama4** [bama4/simple-http-server#6]
**Description**
This ticket involves implementing a queue library. The `queue` library should be a separate folder under the `utils` top level directory.

This `queue` library should be linked with all of the other util packages into one library called `libutils.so`

**Goal**
The following functions are created for the queue:
- [x] queue_t * init_queue() to initialize an empty queue
- [x] void enqueue(void * item, queue_t * queue) to add an item to a queue
- [x] void * dequeue(queue_t * queue) to remove an item from a queue and return it
- [x] void del_queue(queue_t * queue) to delete a queue and free up any memory associated with constructing the queue (NOT freeing the void * data stored) 

Also:
- [ ] Write unit tests for the queue

**Comment by garfr** [comment]
If we are not going to give the queue implementation its own directory, should we put it in a ``utils`` directory, or should we just place it in the socket_tcp_manager folder for simplicity's sake?

Is the implementation just going to store a typeless pointer to the object, or should we also give it a certain size and have the queue structure actually contain the data?

**Comment by bama4** [comment]
My thought is that queue, hashmap, task struct would all be in one `` utils `` folder.
This may also make the project more structured when we add the unit test code and add a run tests option to the build.

So I have seen queue structures in C implemented as a linked list. This would help to keep track of size and for later deletion. In this scenario, each node would just have a pointer to `` void *`` data.

**Comment by garfr** [comment]
From an algorithms point of view, a singly linked list should be the best for the queue, as long as we just hold a pointer to the head and tail.  Then insertion to the back and deletion from the front is O(1).

There is also a chance that a resizable array could utilize cache locality better, but that would require some benchmarking to see if that works out in our case.

**Comment by bama4** [comment]
> From an algorithms point of view, a singly linked list should be the best for the queue, as long as we just hold a pointer to the head and tail. Then insertion to the back and deletion from the front is O(1).
> 
> There is also a chance that a resizable array could utilize cache locality better, but that would require some benchmarking to see if that works out in our case.

Yes I think for our purposes the queue will be fine. We can always improve later
